### ISSUE TITLE
Extension "Biome" is configured as formatter but it cannot format 'TypeScript JSX'-files

### ISSUE THREAD

**Issue by raix** [biomejs/biome-vscode#373]
### VS Code version

1.93.1

### Extension version

2024.9.200949

### Biome version

1.9.2

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

Updated Biome from `1.8.3` and VS Code extension to pre-release for better support of workspaces. We currently use a workaround in [PlatformPlatform](https://github.com/platformplatform/PlatformPlatform)

### Steps to reproduce

* Clone [PlatformPlatform](https://github.com/platformplatform/PlatformPlatform)
* Update settings for the new VS Code extension:
```json
  "biome.enabled": true,
  "biome.lsp.trace.server": "verbose",
  "biome.lsp.bin": "application/node_modules/.bin/biome",
  "biome.projects": [
    {
      "folder": "application",
      "path": "application",
      "configFile": "biome.json"
    }
  ],
  "biome.requireConfigFile": true
```
* Update the Biome version in `application/package.json`
* Change the formatting / indention in one of the `tsx` files
* Right click and choose "format document"

See:
![CleanShot 2024-09-30 at 21 39 49](https://github.com/user-attachments/assets/4de73768-d679-454b-b03b-3285f02c77cf)

### Expected behavior

The document should re format as the CLI tool would do e.g. `npm run format`

### Does this issue occur when using the CLI directly?

No

### Link to a minimal reproduction

https://github.com/platformplatform/PlatformPlatform

### Logs

```plain text
2024-09-30 21:23:40.701 [info] Biome extension 2024.9.200949 activated
2024-09-30 21:23:40.701 [info] Biome extension started
2024-09-30 21:23:40.701 [info] User-facing commands registered
2024-09-30 21:23:40.701 [info] Started listening for lockfile changes
2024-09-30 21:23:40.701 [info] Started listening for configuration changes
2024-09-30 21:23:40.701 [info] Started listening for active text editor changes

---

npx biome rage --daemon-logs
CLI:
  Version:                      1.9.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.8.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.8.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.8.1

Server:
  Status:                       stopped

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.8.2

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.8.3

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.9.1

Incompatible Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ Rage discovered this running server using an incompatible version of Biome.

Server:
  Version:                      1.9.0
```

**Comment by mkromann** [comment]
Having the same issue this morning

**Comment by ematipico** [comment]
Thank you, @raix, for the report. However, we would appreciate it if you could create a minimal reproduction instead of providing a massive repository. A minimal reproduction would remove possible user/environment options that could tarnish the project.

To create a reproduction, you can use our new CLI tool, which should help you to create a very quick repository with what you need: `npm create @biomejs/biome-reproduction`

**Comment by raix** [comment]
@ematipico I've created and pushed a [Minimal reproduction](https://github.com/raix/biome-repro-1727796280038) using your CLI tool

**Comment by nhedger** [comment]
I believe I've found the issue. I'll patch it this morning and release a new pre-release. I'll also update this issue with an explanation.

**Comment by nhedger** [comment]
### New release

I've released a new pre-release version, which I believe fixes this issue.

### What happened

When the extension generates a document selector to filter which document should be taken into account by a given LSP session, it uses the `path` specified in the configuration and appends a glob pattern to it.

```
${project.path}**/*
```

When the `path` contains a trailing `/`, the glob pattern is valid, but if the path does not contain the trailing `/`, the glob pattern is invalid, which causes VS Code to say that Biome cannot format the file, as it is ignored.

https://github.com/biomejs/biome-vscode/blob/becbd5a4d05d3edd00d074607c063a6edfa1f976/src/session.ts#L350-L354

### Fix

I'm now joining all path elements using `Uri`, which should gracefully handle all sorts of quirks such as missing or duplicate trailing `/`.

https://github.com/biomejs/biome-vscode/blob/f9aa11226fd6a940f8dcbf0cb2ac951f894983b7/src/session.ts#L350-L357

**Comment by nhedger** [comment]
@raix Feel free to close the issue once/if you've been able to confirm that it fixes the issue.

**Comment by raix** [comment]
@nhedger When testing the VS Code extension version `v2024.10.20458` the issue is still there when testing the minimal reproduction repo

**Comment by nhedger** [comment]
Hum, could you try removing `"folder": "application",` from your settings. This is meant only for project that use multi-root workspaces. Not sure if this creates another issue.

**Comment by raix** [comment]
@nhedger if I remove the "folder" setting I get:
![CleanShot 2024-10-02 at 12 27 43](https://github.com/user-attachments/assets/4479f5b5-0a6b-42c7-a6ac-60cb6b77bb46)

**Comment by nhedger** [comment]
I've been trying to reproduce this error and encountered it once or twice, but I cannot find a way to trigger it consistently. Are you able to?

**Comment by raix** [comment]
@nhedger yes, I never experienced it to work.

Does the extension register for being able to handle TypeScript files?

**Comment by nhedger** [comment]
Sorry, I meant: are you able to reproduce the error seen in your screenshot?

If so, any information that leads to this error happening would help troubleshooting the issue. Using your reproduction repo and the same OS, I can't seem to reproduce. Wondering if other factors are at play here.

The inability of handling typescript files here is a direct consequence of the extension failing to start properly, but it does work under normal circumstances.

**Comment by raix** [comment]
> Sorry, I meant: are you able to consistently reproduce the error seen in your screenshot?

Yes, I always get the dialog regarding configuring a formatter

> If so, any information that leads to this error happening would help troubleshooting the issue. Using your reproduction repo and the same OS, I can't seem to reproduce. Wondering if other factors are at play here.

Not sure what I'm looking for tbh. I've tried reinstalling the extension, restarting VS Code, looking in devtools - all clues have been added to this issue.

Thinking of differences - I do not have biome installed globally, only in the project node_modules folder

> The inability of handling typescript files here is a direct consequence of the extension failing to start properly, but it does work under normal circumstances.

The extension seems to be running
![CleanShot 2024-10-05 at 23 19 46](https://github.com/user-attachments/assets/7f0d0cd6-5f09-42fa-984d-bd80207b4122)

**Comment by raix** [comment]
Also get the issue when debugging the extension - I do wonder if active project should be undefined when the tsx file is open/selected etc.
![CleanShot 2024-10-06 at 00 09 21](https://github.com/user-attachments/assets/8b5f7818-6be2-457b-9bec-8bfd21c9581f)

**Comment by raix** [comment]
After debugging the extension I found this to be working:

Findings:
```diff
{
  "biome.enabled": true,
  "biome.projects": [
    {
      "path": "application",
-    "folder": "application",
-      "configFile": "biome.json"
+      "configFile": "application/biome.json"
    }
  ],
  "biome.requireConfigFile": true
}
```

Notes:
* It was unexpected that the configFile was not relative to path, but relative to the workspace.

**Comment by nhedger** [comment]
Oh, interesting. I would also have expected that config file to be resolved relative to the path. I'll look into this.

**Comment by codyspate** [comment]
In case it helps the debugging here's my experience with this issue so far.

I'm on Fedora, experiencing the same issue, but its not just for Typescript-JSX. It seems like its pretty much every file 

Linux: Fedora 41
VSCode: 1.94.2
Biome Extension: v2.3.0 (also tried pre-release v2024.10.131712)

**Comment by codyspate** [comment]
^^^ It works after specifying `"biome.lspBin": "node_modules/.bin/biome"` in the workspace settings

**Comment by KKhanhH** [comment]
@nhedger I'm also getting the same issue with the extension for one of my workspace folders. It seems to occur regardless of whether the workspace is a multifolder workspace or the subfolder is opened directly. Looking at the LSP Trace, the logs show that the workspace directory has Windows trailing backslashes, and the extension is adding an additional forward slash before looking for the biome.json file.

```
2024-11-15 11:30:35.394 [info] [Trace - 11:30:35 AM] Received request 'client/registerCapability - (13)'.
2024-11-15 11:30:35.394 [info] Params: {
    "registrations": [
        {
            "id": "biome_did_change_extension_settings",
            "method": "workspace/didChangeConfiguration"
        },
        {
            "id": "biome_range_formatting",
            "method": "textDocument/rangeFormatting"
        },
        {
            "id": "biome_on_type_formatting",
            "method": "textDocument/onTypeFormatting",
            "registerOptions": {
                "documentSelector": null,
                "firstTriggerCharacter": "}",
                "moreTriggerCharacter": [
                    "]",
                    ")"
                ]
            }
        },
        {
            "id": "biome_formatting",
            "method": "textDocument/formatting"
        },
        {
            "id": "biome_did_change_workspace_settings",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "c:\\Users\\username\\Projects\\project_name\\/biome.json",
                        "kind": 7
                    },
                    {
                        "globPattern": "c:\\Users\\username\\Projects\\project_name\\/biome.jsonc",
                        "kind": 7
                    },
                    {
                        "globPattern": "c:\\Users\\username\\Projects\\project_name\\/.editorconfig",
                        "kind": 7
                    },
                    {
                        "globPattern": "c:\\Users\\username\\Projects\\project_name\\/rome.json",
                        "kind": 7
                    }
                ]
            }
        }
    ]
}
```

**Comment by KKhanhH** [comment]
Sorry, ignore what I said previously, I created a minimal repro and the issue isn't caused by a trailing slash it looks like. There seems to be an issue with pnpm workspaces, the extension doesn't detect files inside the packages folder, but it seems to be able to detect files inside .vscode folder and everything else fine.

Here is the repro:
https://github.com/KKhanhH/biome_repro

**Comment by XionWCFM** [comment]
I am also experiencing a similar problem in pnpm workspace after upgrading to 1.9.3.
 
I downgraded to version 1.8.3, which previously worked well, and the biome extension and formatter began to be recognized normally.

Has this problem been resolved?

**Comment by nhedger** [comment]
> Sorry, ignore what I said previously, I created a minimal repro and the issue isn't caused by a trailing slash it looks like. There seems to be an issue with pnpm workspaces, the extension doesn't detect files inside the packages folder, but it seems to be able to detect files inside .vscode folder and everything else fine.
> 
> Here is the repro: https://github.com/KKhanhH/biome_repro

Sorry, but I cannot reproduce. Biome correctly reports diagnostics for `packages/main/index.tsx` for example.

**Comment by nhedger** [comment]
> I am also experiencing a similar problem in pnpm workspace after upgrading to 1.9.3.
> 
> I downgraded to version 1.8.3, which previously worked well, and the biome extension and formatter began to be recognized normally.
> 
> Has this problem been resolved?

Please open a dedicated issue with a minimal reproduction.

**Comment by KKhanhH** [comment]
> > Sorry, ignore what I said previously, I created a minimal repro and the issue isn't caused by a trailing slash it looks like. There seems to be an issue with pnpm workspaces, the extension doesn't detect files inside the packages folder, but it seems to be able to detect files inside .vscode folder and everything else fine.
> > Here is the repro: https://github.com/KKhanhH/biome_repro
> 
> Sorry, but I cannot reproduce. Biome correctly reports diagnostics for `packages/main/index.tsx` for example.

I'm not sure if it makes a difference, but I'm also using pnpm as well, and not npm. Running pnpm biome check in CLI gives the correct error reports while using the pre-release extension with the provided .vscode workspace settings after running "pnpm i" seems to not allow it to format the index.tsx file.

**Comment by somonek** [comment]
in my case the problem was solved after deleting the socket file(s) from here (macos only):
`/Users/[username]/Library/Caches/dev.biomejs.biome`

**Comment by tats-u** [comment]
This is not Mac specific. Occurs in Windows, too.

**Comment by tonivj5** [comment]
I'm having exactly the same problem but with json files... 

![Image](https://github.com/user-attachments/assets/00e1f60d-9a1a-413e-8a7e-f06b76b22408)

**Comment by tats-u** [comment]
Biome started skipping format every kind of file.
Normal TS files can't be formatted either.

**Comment by Mayan-t** [comment]
> ~I'm having exactly the same problem but with json files...~
> 
> ![Image](https://github.com/user-attachments/assets/00e1f60d-9a1a-413e-8a7e-f06b76b22408)
> 
> After restart vscode, plugin worked fine! 😅 the plugin returned the same error for every file (typescript not jsx too)

Does it work for jsons a few levels deep in folder structure?

**Comment by tonivj5** [comment]
> > ~I'm having exactly the same problem but with json files...~
> > ![Image](https://github.com/user-attachments/assets/00e1f60d-9a1a-413e-8a7e-f06b76b22408)
> > After restart vscode, plugin worked fine! 😅 the plugin returned the same error for every file (typescript not jsx too)
> 
> Does it work for jsons a few levels deep in folder structure?

yep, currently it's working with all files

**Comment by nhedger** [comment]
There was an issue with how the document selector glob was created under windows. 

Commit b583860532d38ddbd16914d20ce612c41c9dec4e should fix it.

You may try the latest pre-release. In the meantime, I'm going to close this issue.

If you encounter a similar issue, please open a dedicated issue with a minimal reproduction.

**Comment by henry-dorsia** [comment]
still getting this issue

**Comment by bombillazo** [comment]
Hello, I am experiencing this issue as well.

**Comment by ianram0s** [comment]
I fixed this issue by downgrading the VSCode extension to 2.3.2

**Comment by tecoad** [comment]
> I fixed this issue by downgrading the VSCode extension to 2.3.2

Indeed having this issue and the only thing that solved was downgrading to 2.3.2

**Comment by chicoluan** [comment]
> in my case the problem was solved after deleting the socket file(s) from here (macos only): `/Users/[username]/Library/Caches/dev.biomejs.biome`

This helped me a lot

**Comment by l4stflowers** [comment]
> in my case the problem was solved after deleting the socket file(s) from here (macos only): /Users/[username]/Library/Caches/dev.biomejs.biome

Me too. This helped me a lot. Thanks.
