### ISSUE TITLE
🐛 Unable to use Biome format outside of a workspace with a biome.json file

### ISSUE THREAD

**Issue by baptisteArno** [biomejs/biome-vscode#387]
### VS Code version

1.95.0

### Extension version

2024.10.40751

### Biome version

Can't find it

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

Whenever I try to format a standalone file (tried with json and js), it says

```
Extension 'Biome' is configured as formatter but it cannot format 'JavaScript'-files
```

Here are my user settings:

```json
"editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescript]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[json]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[css]": {
    "editor.defaultFormatter": "biomejs.biome"
  }
```

### Steps to reproduce

I guess just open a standalone file that is not part of a project that has biome installed

### Expected behavior

To format docs

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
Please provide a minimal reproduction @baptisteArno

**Comment by baptisteArno** [comment]
https://github.com/user-attachments/assets/30f01b0a-d25e-47dd-9fb4-93f1dd303890

**Comment by ematipico** [comment]
Sorry @baptisteArno, but this isn't a reproduction. We need a reproduction so **we** can reproduce the issue and debug it.

To create a reproduction, you can use our new CLI tool, which should help you to create a very quick repository with what you need: `npm create @biomejs/biome-reproduction`

**Comment by ematipico** [comment]
As you can notice from the video, the extension didn't enable Biome because the event enables and spawns the Biome server wasn't triggered. When Biome is enabled, you should see `Biome` in the bottom left. This is expected (maybe things have changed in the preview release).

**Comment by baptisteArno** [comment]
Correct me if I am wrong but I don't think I can create a code reproduction for that particular issue since it is not tied to a specific workspace / biome setting. To reproduce it, we even need the `biome.json` file not to be there. It just needs plain VSCode Insiders + Biome pre-release to reproduce it.

Sometimes, a reproduction is just a step-by-step instructions

1. In VSCode Insiders, install Biome extension
2. Create new file with the following content `console.log("Hello world")`
4. Biome is not enabled even though the file was autodetected as Javscript and even if we specific the Javascript file type, Biome does not launch

**Comment by ematipico** [comment]
Thank you. The step-by-step instructions are also a valid reproduction. This information should have been present in the initial description.

**Comment by a1245582339** [comment]
Same with you
<img width="931" alt="image" src="https://github.com/user-attachments/assets/1c513e3d-54b3-4b45-85d3-35c7e2457219">

**Comment by nhedger** [comment]
This may have been fixed by c146d1bf9bdcec376706114d76abdb11d7e9005e.

Please try the latest pre-release, which includes the fix.

**Comment by Dtesch9** [comment]
Same issue here, still happening, even with the latest pre-release, looks like the extensions is not considering my biome.jsonc at all, besides, it only works with `editor.defaultFormatter": "vscode.typescript-language-features` instead of `editor.defaultFormatter": "biomejs.biome` for some reason I'm not aware of.
