### ISSUE TITLE
🐛 Not working for Tailwind CSS files

### ISSUE THREAD

**Issue by wottpal** [biomejs/biome-vscode#388]
### VS Code version

0.41.3 (Cursor)

### Extension version

2.3.0

### Biome version

1.9.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

I don't get the extension to format/lint my CSS files (the Biome CLI works) despite having this in my VSCode settings:

```json
  "[css]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
```

![CleanShot 2024-10-08 at 16 54 06@2x](https://github.com/user-attachments/assets/aa4f016b-931f-43a8-b32d-3d7751d517f6)

The extension is working seamlessly for all other file types.

And I'm not having any stuff ignored in `biome.js`.

### Steps to reproduce

see above

### Expected behavior

see above

### Does this issue occur when using the CLI directly?

No

**Comment by ematipico** [comment]
To create a reproduction, you can use our new CLI tool, which should help you to create a very quick repository with what you need: `npm create @biomejs/biome-reproduction`

**Comment by wottpal** [comment]
Did create a repro here: https://github.com/wottpal/biome-repro-1728407341600 – But it's really just a very plain project with some VSCode settings (that work for all other extensions). 

Btw, would suggest adding a `.gitignore` with your CLI as well.

**Comment by nhedger** [comment]
If I'm not mistaken, the language identifier of your file is "Tailwind CSS". The tailwindcss extension may be taking over. You may have to force the CSS assignment for .css files.

**Comment by ematipico** [comment]
> Did create a repro here: https://github.com/wottpal/biome-repro-1728407341600 – But it's really just a very plain project with some VSCode settings (that work for all other extensions). 
> 
> Btw, would suggest adding a `.gitignore` with your CLI as well. 

Also, tailwind CSS files use unofficial syntax, so you're better off ignoring these files from Biome

**Comment by wottpal** [comment]
Oh, that seems to be the case indeed. Good catch!

But tbh that's the default for _a lot_ of projects these days and also the recommended way when using Tailwind CSS. 

It also seems to be supported at least did everything work seamlessly with Biome when switching to CSS (though I get warnings about the `@`-rules now and use all the Tailwind features).

I would reframe this issue then to support Tailwind CSS (`tailwindcss`) type within the extension (again, CLI works fine).

**Comment by nhedger** [comment]
To work around this issue, we could add `tailwindcss` as a supported language, but we want to ensure the parser won't choke on them.

**Comment by wottpal** [comment]
But even though `tailwindcss` is not an actual file extension (the file name still ends with `.css` and works just fine with Biomes CLI). It's just kind of an ephermal language for their extension purposes, so IMO it sounds as an extension thing.

Is there any workaround I can do right now on my end to get this working (and keeping Tailwind CSS)?

**Comment by nhedger** [comment]
You're correct, I was thinking of something else.

Fixed in [f2c4e1a](https://github.com/biomejs/biome-vscode/commit/f2c4e1a2d6b091cf88c5c06d7bb774f3dad272b9). Will release a new pre-release in a bit.

**Comment by joseavr** [comment]
I still have this issue. How can I fix it?

![CleanShot 2024-10-25 at 05 54 30@2x](https://github.com/user-attachments/assets/8705760a-1037-44fb-a8cd-47a8dd81f90b)

**Comment by mike-moreau** [comment]
Is it working if you switch to the pre-release version of the extension?

**Comment by wottpal** [comment]
> Is it working if you switch to the pre-release version of the extension?

Yes, this is what I did!

**Comment by depsimon** [comment]
Using pre-release version with biome 2.0.0-beta.2, I have issues with CSS files when the language is "tailwindcss". If I switch back to "css" as the language, the extension works fine.

```
[info] [Error - 4:59:18 PM] Request textDocument/codeAction failed.
[info]   Message: The file does not exist in the workspace.
  Code: -32603 
Error(Diagnostic { path: Some(File("file:///Users/simon/Code/Github/project/src/styles/app.css")), source: The file does not exist in the workspace. })
[info] [Error - 4:59:18 PM] Request textDocument/codeAction failed.
[info]   Message: The file does not exist in the workspace.
  Code: -32603 
Error(Diagnostic { path: Some(File("file:///Users/simon/Code/Github/project/src/styles/app.css")), source: The file does not exist in the workspace. })
[info] [Error - 4:59:18 PM] file:///Users/simon/Code/Github/project/src/styles/app.css internalError/fs  INTERNAL  ━━━━━━━━━━

  × The file does not exist in the workspace.
  
  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
```

```
# Trace
[info] [Trace - 4:59:18 PM] Sending request 'textDocument/codeAction - (7)'.
[info] Params: {
    "textDocument": {
        "uri": "file:///Users/simon/Code/Github/project/src/styles/app.css"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 12,
            "character": 0
        }
    },
    "context": {
        "diagnostics": [],
        "only": [
            "quickfix.biome"
        ],
        "triggerKind": 2
    }
}


[info] [Trace - 4:59:18 PM] Received response 'textDocument/codeAction - (7)' in 2ms. Request failed: The file does not exist in the workspace. (-32603).
[info] Error data: "Error(Diagnostic { path: Some(File(\"file:///Users/simon/Code/Github/project/src/styles/app.css\")), source: The file does not exist in the workspace. })"
```

Here's some relevant VS Code settings:

```json
{
  "[css][tailwindcss]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit",
    "source.removeUnusedImports": "always"
  },
  "editor.formatOnSave": true,
  "files.associations": {
    "*.css": "tailwindcss"
  },
}
```

**Comment by daveycodez** [comment]
> Using pre-release version with biome 2.0.0-beta.2, I have issues with CSS files when the language is "tailwindcss". If I switch back to "css" as the language, the extension works fine.
> 
> ```
> [info] [Error - 4:59:18 PM] Request textDocument/codeAction failed.
> [info]   Message: The file does not exist in the workspace.
>   Code: -32603 
> Error(Diagnostic { path: Some(File("file:///Users/simon/Code/Github/project/src/styles/app.css")), source: The file does not exist in the workspace. })
> [info] [Error - 4:59:18 PM] Request textDocument/codeAction failed.
> [info]   Message: The file does not exist in the workspace.
>   Code: -32603 
> Error(Diagnostic { path: Some(File("file:///Users/simon/Code/Github/project/src/styles/app.css")), source: The file does not exist in the workspace. })
> [info] [Error - 4:59:18 PM] file:///Users/simon/Code/Github/project/src/styles/app.css internalError/fs  INTERNAL  ━━━━━━━━━━
> 
>   × The file does not exist in the workspace.
>   
>   ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
> ```
> 
> ```
> # Trace
> [info] [Trace - 4:59:18 PM] Sending request 'textDocument/codeAction - (7)'.
> [info] Params: {
>     "textDocument": {
>         "uri": "file:///Users/simon/Code/Github/project/src/styles/app.css"
>     },
>     "range": {
>         "start": {
>             "line": 0,
>             "character": 0
>         },
>         "end": {
>             "line": 12,
>             "character": 0
>         }
>     },
>     "context": {
>         "diagnostics": [],
>         "only": [
>             "quickfix.biome"
>         ],
>         "triggerKind": 2
>     }
> }
> 
> 
> [info] [Trace - 4:59:18 PM] Received response 'textDocument/codeAction - (7)' in 2ms. Request failed: The file does not exist in the workspace. (-32603).
> [info] Error data: "Error(Diagnostic { path: Some(File(\"file:///Users/simon/Code/Github/project/src/styles/app.css\")), source: The file does not exist in the workspace. })"
> ```
> 
> Here's some relevant VS Code settings:
> 
> {
>   "[css][tailwindcss]": {
>     "editor.defaultFormatter": "biomejs.biome"
>   },
>   "editor.codeActionsOnSave": {
>     "quickfix.biome": "explicit",
>     "source.organizeImports.biome": "explicit",
>     "source.removeUnusedImports": "always"
>   },
>   "editor.formatOnSave": true,
>   "files.associations": {
>     "*.css": "tailwindcss"
>   },
> }

Same issue after migrating from 1.9.4 to 2.0.0 beta... I think we need a new issue opened for this

**Comment by wottpal** [comment]
Yes, I think so too! It's not working for me (again), too after migration.

Done: https://github.com/biomejs/biome-vscode/issues/632

**Comment by mehdad-hussain** [comment]
Same here CSS file but to use tailwind feature when change language mode to tailwind CSS biome code not format that file on save but can do with write command, pls need help with this issue
