### ISSUE TITLE
🐛 Biome Vscode Multiplies Itself

### ISSUE THREAD

**Issue by Alec2435** [biomejs/biome-vscode#542]
### VS Code version

1.96.2

### Extension version

2.3.2

### Biome version

1.9.4

### Operating system

- [ ] Windows
- [x] macOS
- [ ] Linux

### Description

See the following screenshots to see what I mean, but basically after running my editor for a while without restarting or reloading, it seems like multiple instances of the Biome extension start and they cause multiple errors for each lint/format issue. They also conflict with each other when formatting on save causing the file to end up quite messed up (as shown below).

<img width="327" alt="Image" src="https://github.com/user-attachments/assets/81163c17-bae5-408b-93b0-c99e43f77d1e" />

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/6e814394-d18a-4e74-a34d-74199a2a1cbb" />

After format on save:

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/ac02bf65-2fe9-4a0e-8870-e802c2e023f0" />

### Steps to reproduce

I don't have clear reproduction steps, but it consistently happens in a VSCode instance that runs for more than a day or so (especially if the Mac hibernates during that time)

### Expected behavior

A single biome instance runs and doesn't cause the duplicate formatting attempts or errors/warnings.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stderr] end
[cli] exit 0
[cli-stderr] finish
[cli-stderr] close
[cli-stdout] end
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stdout] finish
[cli] close 0
[cli-stdout] close
[Info  - 9:50:44 AM] Server initialized with PID: 6896
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli-stderr] close
[cli] exit 0
[cli] close 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[Info  - 9:53:20 AM] Server initialized with PID: 6896
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 9:53:35 AM] Server initialized with PID: 6896
[Info  - 9:53:35 AM] Server initialized with PID: 6896
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 9:53:44 AM] Server initialized with PID: 6896
[Info  - 9:53:44 AM] Server initialized with PID: 6896
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 10:43:27 AM] Server initialized with PID: 6896
[Info  - 10:43:27 AM] Server initialized with PID: 6896
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 10:43:28 AM] Server initialized with PID: 6896
[Info  - 10:43:28 AM] Server initialized with PID: 6896
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stderr] end
[cli-stdout] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] finish
[cli-stdout] close
[cli-stdout] close
[cli-stderr] close
[cli] close 0
[cli-stderr] close
[cli] exit 0
[cli] close 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[Info  - 10:43:32 AM] Server initialized with PID: 6896
[Info  - 10:43:32 AM] Server initialized with PID: 6896
[Warn  - 10:45:24 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 10:47:00 AM] Server initialized with PID: 6896
[Info  - 10:47:00 AM] Server initialized with PID: 6896
[Warn  - 10:47:06 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
[Warn  - 10:47:11 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
Reloading biome executable.
Reloading biome executable.
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Biome binary found at /Users/alecv/dev/newform/newform-internal/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/alecv/Library/Application%20Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
Executing Biome from: /Users/alecv/Library/Application Support/Cursor/User/workspaceStorage/5edd49af7c2823eb95b156d5ca5be9aa/biomejs.biome/biome
[cli-stdout] data 65
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 10:47:56 AM] Server initialized with PID: 6896
[Info  - 10:47:56 AM] Server initialized with PID: 6896
[Warn  - 10:59:02 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
[Warn  - 11:00:26 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
[cli-stdout] data 65
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/Users/alecv/Library/Caches/dev.biomejs.biome/biome-socket-1.9.4" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[Info  - 11:00:48 AM] Server initialized with PID: 6896
[Warn  - 11:00:49 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
[Warn  - 11:06:20 AM] Code formatting aborted due to parsing errors. To format code with errors, enable the 'formatter.formatWithErrors' option.
```

**Comment by nhedger** [comment]
Hey, this is a known issue with the current stable version of the extension.

You may want to try the pre-release extension which should solve this.

**Comment by kucho** [comment]
> Hey, this is a known issue with the current stable version of the extension.
> 
> You may want to try the pre-release extension which should solve this.

This is still happening with the pre-release extension. I was able to reproduce the problem consistently:

https://github.com/user-attachments/assets/f847fc03-368f-43ca-b19c-7a3afde36600

It happens every time the window reloads. I noticed it happening when my other extensions get updated too.

**Comment by nhedger** [comment]
The pre-release isn't up to date. Can you still reproduce this in the latest stable version of the extension?

**Comment by kucho** [comment]
> The pre-release isn't up to date. Can you still reproduce this in the latest stable version of the extension?

I can confirm it's fixed for me. Likewise, trying to format `settings.json` wasn't working before either, but now it's working fine. Thank you!
